package com.pdsa.games.common.algorithm;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@RequestMapping("/api/algorithms")
@Tag(name = "Algorithms", description = "Create and list algorithms")
public class AlgorithmController {

    private final AlgorithmService algorithmService;

    public AlgorithmController(AlgorithmService algorithmService) {
    this.algorithmService = algorithmService;
    }

    @PostMapping
    @Operation(
        summary = "Create an algorithm",
        description = "Creates a new algorithm. The `algorithmId` must be omitted because it is generated by the server.",
        requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
            required = true,
            description = "Algorithm payload used to create a new algorithm",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = AlgorithmModel.class),
                examples = @ExampleObject(
                    name = "Create algorithm request",
                    value = "{\n  \"algorithmName\": \"Backtracking\",\n  \"gameId\": 1\n}"
                )
            )
        )
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "201",
            description = "Algorithm created successfully",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = AlgorithmModel.class),
                examples = @ExampleObject(
                    name = "Create algorithm response",
                    value = "{\n  \"algorithmId\": 1,\n  \"algorithmName\": \"Backtracking\",\n  \"gameId\": 1\n}"
                )
            )
        ),
        @ApiResponse(
            responseCode = "400",
            description = "Invalid request body (for example, `algorithmId` was provided manually or `gameId` does not reference an existing game)",
            content = @Content(
                mediaType = "application/problem+json",
                schema = @Schema(implementation = ProblemDetail.class),
                examples = @ExampleObject(
                    name = "Validation error",
                    value = "{\n  \"type\": \"about:blank\",\n  \"title\": \"Bad Request\",\n  \"status\": 400,\n  \"detail\": \"algorithmId must not be provided when creating an algorithm\"\n}"
                )
            )
        ),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<AlgorithmModel> createAlgorithm(@RequestBody AlgorithmModel algorithm) {
    AlgorithmModel savedAlgorithm = algorithmService.saveAlgorithm(algorithm);
    return ResponseEntity.status(HttpStatus.CREATED).body(savedAlgorithm);
    }

    @GetMapping
    @Operation(
        summary = "List algorithms",
        description = "Returns all algorithms currently stored in the system."
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Algorithms retrieved successfully",
            content = @Content(
                mediaType = "application/json",
                array = @ArraySchema(schema = @Schema(implementation = AlgorithmModel.class))
            )
        ),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<List<AlgorithmModel>> getAllAlgorithms() {
    return ResponseEntity.ok(algorithmService.getAllAlgorithms());
    }

    @GetMapping("/game/{gameId}")
    @Operation(
        summary = "List algorithms by game id",
        description = "Returns all algorithms linked to the specified game id."
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Algorithms retrieved successfully",
            content = @Content(
                mediaType = "application/json",
                array = @ArraySchema(schema = @Schema(implementation = AlgorithmModel.class))
            )
        ),
        @ApiResponse(responseCode = "404", description = "No algorithms found for the provided game id"),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<List<AlgorithmModel>> getAlgorithmsByGameId(
        @Parameter(description = "Unique game identifier", example = "1")
        @PathVariable Integer gameId) {
    List<AlgorithmModel> algorithms = algorithmService.getAlgorithmsByGameId(gameId);
    if (algorithms.isEmpty()) {
        return ResponseEntity.notFound().build();
    }

    return ResponseEntity.ok(algorithms);
    }

    @GetMapping("/{algorithmId}")
    @Operation(
        summary = "Get algorithm by id",
        description = "Fetches a single algorithm by its unique identifier."
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Algorithm found",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = AlgorithmModel.class))
        ),
        @ApiResponse(responseCode = "404", description = "No algorithm exists with the provided id"),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<AlgorithmModel> getAlgorithmById(
        @Parameter(description = "Unique algorithm identifier", example = "1")
        @PathVariable Integer algorithmId) {
    return algorithmService.getAlgorithmById(algorithmId)
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
    }

    @PutMapping("/{algorithmId}")
    @Operation(
        summary = "Replace algorithm",
        description = "Fully updates the algorithm identified by `algorithmId` and returns the updated resource."
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Algorithm updated successfully",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = AlgorithmModel.class))
        ),
        @ApiResponse(
            responseCode = "400",
            description = "Invalid request body (for example, path and body ids do not match)",
            content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
        ),
        @ApiResponse(responseCode = "404", description = "No algorithm exists with the provided id"),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<AlgorithmModel> updateAlgorithm(
        @Parameter(description = "Unique algorithm identifier", example = "1")
        @PathVariable Integer algorithmId,
        @RequestBody AlgorithmModel algorithm) {
    return algorithmService.updateAlgorithm(algorithmId, algorithm)
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
    }

    @PatchMapping("/{algorithmId}")
    @Operation(
        summary = "Partially update algorithm",
        description = "Partially updates mutable fields of the algorithm identified by `algorithmId`."
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Algorithm updated successfully",
            content = @Content(mediaType = "application/json", schema = @Schema(implementation = AlgorithmModel.class))
        ),
        @ApiResponse(
            responseCode = "400",
            description = "Invalid patch body (for example, no updatable fields provided or id mismatch)",
            content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
        ),
        @ApiResponse(responseCode = "404", description = "No algorithm exists with the provided id"),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<AlgorithmModel> patchAlgorithm(
        @Parameter(description = "Unique algorithm identifier", example = "1")
        @PathVariable Integer algorithmId,
        @RequestBody AlgorithmModel algorithm) {
    return algorithmService.patchAlgorithm(algorithmId, algorithm)
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
    }

    @DeleteMapping("/{algorithmId}")
    @Operation(
        summary = "Delete algorithm",
        description = "Deletes the algorithm for the given id."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "204", description = "Algorithm deleted successfully"),
        @ApiResponse(responseCode = "404", description = "No algorithm exists with the provided id"),
        @ApiResponse(responseCode = "500", description = "Unexpected server error")
    })
    public ResponseEntity<Void> deleteAlgorithm(
        @Parameter(description = "Unique algorithm identifier", example = "1")
        @PathVariable Integer algorithmId) {
    if (algorithmService.getAlgorithmById(algorithmId).isEmpty()) {
        return ResponseEntity.notFound().build();
    }

    algorithmService.deleteAlgorithm(algorithmId);
    return ResponseEntity.noContent().build();
    }
}
