package com.pdsa.games.common.player;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.pdsa.games.common.security.JwtService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityRequirements;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@RequestMapping("/api/players")
@Tag(name = "Players", description = "Create, list, fetch, update and delete player profiles used by game sessions")
@SecurityRequirement(name = "bearerAuth")
public class PlayerController {

	private final PlayerService playerService;
	private final JwtService jwtService;

	public PlayerController(PlayerService playerService, JwtService jwtService) {
		this.playerService = playerService;
		this.jwtService = jwtService;
	}

	private record PlayerLoginRequest(String playerEmail, String playerPassword) {
	}

	private record PlayerLoginResponse(String tokenType, String accessToken, long expiresInSeconds) {
	}

	@PostMapping("/login")
	@SecurityRequirements(value = {})
	@Operation(
			summary = "Player login",
			description = "Authenticates a player using email and password. Returns a bearer token on success."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Login successful",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = PlayerLoginResponse.class))
			),
			@ApiResponse(responseCode = "400", description = "Missing email or password"),
			@ApiResponse(responseCode = "401", description = "Invalid email or password"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<PlayerLoginResponse> loginPlayer(@RequestBody PlayerLoginRequest loginRequest) {
		return playerService.loginPlayer(loginRequest.playerEmail(), loginRequest.playerPassword())
				.map(player -> ResponseEntity.ok(new PlayerLoginResponse(
						"Bearer",
						jwtService.generateToken(player.getPlayerEmail()),
						jwtService.getExpirationSeconds())))
				.orElseGet(() -> ResponseEntity.status(HttpStatus.UNAUTHORIZED).build());
	}

	@PostMapping
	@SecurityRequirements(value = {})
	@Operation(
			summary = "Create a player",
			description = "Creates a new player profile. The `playerId` must be omitted because it is generated by the server."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "201",
					description = "Player created successfully",
					content = @Content(
							mediaType = "application/json",
							schema = @Schema(implementation = PlayerModel.class),
							examples = @ExampleObject(
									name = "Create player response",
									value = "{\n  \"playerId\": 1,\n  \"playerName\": \"Alice\",\n  \"playerEmail\": \"alice@example.com\"\n}"
							)
					)
			),
			@ApiResponse(
					responseCode = "400",
					description = "Invalid request body (for example, `playerId` was provided manually)",
					content = @Content(
							mediaType = "application/problem+json",
							schema = @Schema(implementation = ProblemDetail.class),
							examples = @ExampleObject(
									name = "Validation error",
									value = "{\n  \"type\": \"about:blank\",\n  \"title\": \"Bad Request\",\n  \"status\": 400,\n  \"detail\": \"playerId must not be provided when creating a player\"\n}"
							)
					)
			),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<PlayerModel> createPlayer(
			@io.swagger.v3.oas.annotations.parameters.RequestBody(
					required = true,
					description = "Player payload used to create a new profile",
					content = @Content(
							mediaType = "application/json",
							schema = @Schema(implementation = PlayerModel.class),
							examples = @ExampleObject(
									name = "Create player request",
									value = "{\n  \"playerName\": \"Alice\",\n  \"playerEmail\": \"alice@example.com\",\n  \"playerPassword\": \"password123\"\n}"
							)
					)
			)
			@RequestBody PlayerModel player) {
		PlayerModel savedPlayer = playerService.savePlayer(player);
		return ResponseEntity.status(HttpStatus.CREATED).body(savedPlayer);
	}

	@GetMapping
	@Operation(
			summary = "List players",
			description = "Returns all player profiles currently stored in the system."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Players retrieved successfully",
					content = @Content(
							mediaType = "application/json",
							array = @ArraySchema(schema = @Schema(implementation = PlayerModel.class))
					)
			),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<List<PlayerModel>> getAllPlayers() {
		return ResponseEntity.ok(playerService.getAllPlayers());
	}

	@GetMapping("/{playerId}")
	@Operation(
			summary = "Get player by id",
			description = "Fetches a single player profile by its unique identifier."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Player found",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = PlayerModel.class))
			),
			@ApiResponse(responseCode = "404", description = "No player exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<PlayerModel> getPlayerById(
			@Parameter(description = "Unique player identifier", example = "1")
			@PathVariable Integer playerId) {
		return playerService.getPlayerById(playerId)
				.map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.notFound().build());
	}

	@PutMapping("/{playerId}")
	@Operation(
			summary = "Replace player",
			description = "Fully updates the player identified by `playerId` and returns the updated resource."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Player updated successfully",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = PlayerModel.class))
			),
			@ApiResponse(
					responseCode = "400",
					description = "Invalid request body (for example, path and body ids do not match)",
					content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
			),
			@ApiResponse(responseCode = "404", description = "No player exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<PlayerModel> updatePlayer(
			@Parameter(description = "Unique player identifier", example = "1")
			@PathVariable Integer playerId,
			@RequestBody PlayerModel player) {
		return playerService.updatePlayer(playerId, player)
				.map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.notFound().build());
	}

	@PatchMapping("/{playerId}")
	@Operation(
			summary = "Partially update player",
			description = "Partially updates mutable fields of the player identified by `playerId`."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Player updated successfully",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = PlayerModel.class))
			),
			@ApiResponse(
					responseCode = "400",
					description = "Invalid patch body (for example, no updatable fields provided or id mismatch)",
					content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
			),
			@ApiResponse(responseCode = "404", description = "No player exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<PlayerModel> patchPlayer(
			@Parameter(description = "Unique player identifier", example = "1")
			@PathVariable Integer playerId,
			@RequestBody PlayerModel player) {
		return playerService.patchPlayer(playerId, player)
				.map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.notFound().build());
	}

	@DeleteMapping("/{playerId}")
	@Operation(
			summary = "Delete player",
			description = "Deletes the player profile for the given id."
	)
	@ApiResponses({
			@ApiResponse(responseCode = "204", description = "Player deleted successfully"),
			@ApiResponse(responseCode = "404", description = "No player exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<Void> deletePlayer(
			@Parameter(description = "Unique player identifier", example = "1")
			@PathVariable Integer playerId) {
		if (playerService.getPlayerById(playerId).isEmpty()) {
			return ResponseEntity.notFound().build();
		}

		playerService.deletePlayer(playerId);
		return ResponseEntity.noContent().build();
	}
}
