package com.pdsa.games.common.game;

import java.util.List;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/games")
@Tag(name = "Games", description = "Create, list, fetch, update and delete games")
public class GameController {

	private final GameService gameService;

	public GameController(GameService gameService) {
		this.gameService = gameService;
	}

	@PostMapping
	@Operation(
			summary = "Create a game",
			description = "Creates a new game. The `gameId` must be omitted because it is generated by the server.",
			requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
					required = true,
					description = "Game payload used to create a new game",
					content = @Content(
							mediaType = "application/json",
							schema = @Schema(implementation = GameModel.class),
							examples = @ExampleObject(
									name = "Create game request",
									value = "{\n  \"gameName\": \"Knight's Tour\"\n}"
							)
					)
			)
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "201",
					description = "Game created successfully",
					content = @Content(
							mediaType = "application/json",
							schema = @Schema(implementation = GameModel.class),
							examples = @ExampleObject(
									name = "Create game response",
									value = "{\n  \"gameId\": 1,\n  \"gameName\": \"Knight's Tour\"\n}"
							)
					)
			),
			@ApiResponse(
					responseCode = "400",
					description = "Invalid request body (for example, `gameId` was provided manually)",
					content = @Content(
							mediaType = "application/problem+json",
							schema = @Schema(implementation = ProblemDetail.class),
							examples = @ExampleObject(
									name = "Validation error",
									value = "{\n  \"type\": \"about:blank\",\n  \"title\": \"Bad Request\",\n  \"status\": 400,\n  \"detail\": \"gameId must not be provided when creating a game\"\n}"
							)
					)
			),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<GameModel> createGame(@RequestBody GameModel game) {
		GameModel savedGame = gameService.saveGame(game);
		return ResponseEntity.status(HttpStatus.CREATED).body(savedGame);
	}

	@GetMapping
	@Operation(
			summary = "List games",
			description = "Returns all games currently stored in the system."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Games retrieved successfully",
					content = @Content(
							mediaType = "application/json",
							array = @ArraySchema(schema = @Schema(implementation = GameModel.class))
					)
			),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<List<GameModel>> getAllGames() {
		return ResponseEntity.ok(gameService.getAllGames());
	}

	@GetMapping("/{gameId}")
	@Operation(
			summary = "Get game by id",
			description = "Fetches a single game by its unique identifier."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Game found",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = GameModel.class))
			),
			@ApiResponse(responseCode = "404", description = "No game exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<GameModel> getGameById(
			@Parameter(description = "Unique game identifier", example = "1")
			@PathVariable Integer gameId) {
		return gameService.getGameById(gameId)
				.map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.notFound().build());
	}

	@PutMapping("/{gameId}")
	@Operation(
			summary = "Replace game",
			description = "Fully updates the game identified by `gameId` and returns the updated resource."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Game updated successfully",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = GameModel.class))
			),
			@ApiResponse(
					responseCode = "400",
					description = "Invalid request body (for example, path and body ids do not match)",
					content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
			),
			@ApiResponse(responseCode = "404", description = "No game exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<GameModel> updateGame(
			@Parameter(description = "Unique game identifier", example = "1")
			@PathVariable Integer gameId,
			@RequestBody GameModel game) {
		return gameService.updateGame(gameId, game)
				.map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.notFound().build());
	}

	@PatchMapping("/{gameId}")
	@Operation(
			summary = "Partially update game",
			description = "Partially updates mutable fields of the game identified by `gameId`."
	)
	@ApiResponses({
			@ApiResponse(
					responseCode = "200",
					description = "Game updated successfully",
					content = @Content(mediaType = "application/json", schema = @Schema(implementation = GameModel.class))
			),
			@ApiResponse(
					responseCode = "400",
					description = "Invalid patch body (for example, no updatable fields provided or id mismatch)",
					content = @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetail.class))
			),
			@ApiResponse(responseCode = "404", description = "No game exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<GameModel> patchGame(
			@Parameter(description = "Unique game identifier", example = "1")
			@PathVariable Integer gameId,
			@RequestBody GameModel game) {
		return gameService.patchGame(gameId, game)
				.map(ResponseEntity::ok)
				.orElseGet(() -> ResponseEntity.notFound().build());
	}

	@DeleteMapping("/{gameId}")
	@Operation(
			summary = "Delete game",
			description = "Deletes the game for the given id."
	)
	@ApiResponses({
			@ApiResponse(responseCode = "204", description = "Game deleted successfully"),
			@ApiResponse(responseCode = "404", description = "No game exists with the provided id"),
			@ApiResponse(responseCode = "500", description = "Unexpected server error")
	})
	public ResponseEntity<Void> deleteGame(
			@Parameter(description = "Unique game identifier", example = "1")
			@PathVariable Integer gameId) {
		if (gameService.getGameById(gameId).isEmpty()) {
			return ResponseEntity.notFound().build();
		}

		gameService.deleteGame(gameId);
		return ResponseEntity.noContent().build();
	}
}
